import argparse
import glob
import hashlib
import json
import math
import os
import re

import spacy
import numpy as np
import pandas as pd
from tqdm import tqdm
from pathlib import Path

from functools import partial
from concurrent.futures import ProcessPoolExecutor, as_completed

from typing import Dict, List, Tuple, Any, Optional



# Pre-compile the regex for better performance
SPEAKER_PATTERN = re.compile(r'^([A-Z][a-z]+ [A-Z][a-z]+)\s*:\s*')
CONLL_LINETAIL = "\t_\t_\t_\t_\t_\t_\t_\t_\n"


# Global NLP object to be initialized in each worker process
_nlp = None



def get_next_quarterdate(datafqrt: str) -> Tuple[str, str, str]:
    """Calculates the first day of the first month of the next fiscal quarter.

    If a fiscal quarter (e.g., '2023Q3') is provided, this function determines 
    the first day of the first month of the subsequent quarter. If the input 
    is the 4th quarter, it rolls over to the 1st quarter of the following year.

    Args:
        datafqrt (str): A string representing the fiscal quarter reported for 
            (expected format: 'YYYYQX', e.g., '2023Q3').

    Returns:
        Tuple[str, str, str]: A tuple containing the next quarter's 
            (year, month, day) as strings.
    """
    quarters = {
        '1': ['01', '01'],
        '2': ['04', '01'],
        '3': ['07', '01'],
        '4': ['10', '01']
    }

    this_year = datafqrt[:4]
    qrt = datafqrt[-1]

    # Check if the current quarter is 1, 2, or 3 to determine the next quarter
    if qrt in ('1', '2', '3'):
        next_qrt = str(int(qrt) + 1)
    else:
        next_qrt = '1'
        this_year = str(int(this_year) + 1)

    this_month, this_day = quarters[next_qrt]
    return this_year, this_month, this_day

def make_arrays(df: pd.DataFrame) -> Dict[str, np.ndarray]:
    """Converts DataFrame columns into a dictionary of NumPy arrays and handles missing date parsing.

    Extract metadata columns from a DataFrame and txt of the transcript. It specifically 
    processes the 'earnings_date' column to extract year, month, and day. If a 
    date is missing or invalid, it falls back to using the 'datafqtr' column 
    via the `get_next_quarterdate` function to estimate the date.

    Args:
        df (pd.DataFrame): A pandas DataFrame containing at least the following columns:
            'company', 'quarter', 'earnings_date', 'datafqtr', and 'transcript'.

    Returns:
        Dict[str, np.ndarray]: A dictionary where keys are string identifiers and 
            values are NumPy arrays containing the extracted data.
            Keys are: 'id_array', 'years_arr', 'months_arr', 'days_arr', 
            'text_array', 'acutaldates_array', 'companies_array', 
            'quarters_array', and 'datafqtr_array'.
    """
    id_array = df.index.values
    companies_array = df['company'].values
    quarters_array = df['quarter'].values
    acutaldates_array = df['earnings_date'].values
    datafqtr_array = df['datafqtr'].values
    text_array = df['transcript'].values

    years_list, days_list, months_list = [], [], []

    for x, date in enumerate(acutaldates_array):
        # Check if date is a valid string format (YYYY-MM-DD)
        if isinstance(date, str) and len(str(date).split("-")) == 3:
            date_str = str(date)
            this_year = date_str.split("-")[0]
            this_month = date_str.split("-")[1]
            this_day = date_str.split("-")[2]
            years_list.append(this_year)
            months_list.append(this_month)
            days_list.append(this_day)
        else:
            # Fallback: use the datafqtr to calculate the next quarter's start date
            item = datafqtr_array[x]
            this_year, this_month, this_day = get_next_quarterdate(item)
            years_list.append(this_year)
            months_list.append(this_month)
            days_list.append(this_day)

    years_arr = np.array(years_list)
    months_arr = np.array(months_list)
    days_arr = np.array(days_list)

    my_arrays = {
        "id_array": id_array,
        "years_arr": years_arr,
        "months_arr": months_arr,
        "days_arr": days_arr,
        "text_array": text_array,
        "acutaldates_array": acutaldates_array,
        "companies_array": companies_array,
        "quarters_array": quarters_array,
        "datafqtr_array": datafqtr_array
    }

    return my_arrays



def make_dicts(
    my_arrays: Dict[str, np.ndarray], 
    parquet_file: str, 
    input_dir: str, 
    output_dir: str, 
    export_jsons: bool = False, 
    verbose: bool = False
) -> Tuple[str, List[Dict[str, Any]], Dict[str, Any]]:
    """Groups data by year into dictionaries and optionally exports them to JSON.

    Process the arrays generated by `make_arrays`, groups the 
    records by year, and organizes them into a nested dictionary structure. 
    If `export_jsons` is True, it saves each year's data into a separate JSON file.

    Args:
        my_arrays (Dict[str, np.ndarray]): Dictionary containing NumPy arrays 
            of the dataset (keys: 'id_array', 'years_arr', etc.).
        parquet_file (str): Path to the source parquet file (used for naming).
        input_dir (str): The base directory for input files.
        export_jsons (bool, optional): Whether to export the grouped data to 
            JSON files. Defaults to False.
        verbose (bool, optional): Whether to print the paths of exported 
            files. Defaults to False.

    Returns:
        Tuple[str, List[Dict[str, Any]], Dict[str, Any]]: A tuple containing:
            - output_dir (str): The path to the directory where JSONs are saved.
            - output_dictlist (List): A list of dictionaries grouped by year.
            - print_info (Dict): Metadata containing the number of year 
              splits and the filename.
    """
    # Setup output directory
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    id_array = my_arrays['id_array']
    years_arr = my_arrays['years_arr']
    months_arr = my_arrays['months_arr']
    days_arr = my_arrays['days_arr']
    text_array = my_arrays['text_array']
    acutaldates_array = my_arrays['acutaldates_array']
    companies_array = my_arrays['companies_array']
    quarters_array = my_arrays['quarters_array']
    datafqtr_array = my_arrays['datafqtr_array']

    source_short = Path(parquet_file).stem
    target_years = sorted(set(years_arr))
    print_info = {'y_splits': len(target_years), 'file': source_short}
    
    # Group data by year in a single pass O(N) instead of O(Y*N)
    grouped_data = {year: {} for year in target_years}
    
    for i in range(id_array.size):
        year = years_arr[i]
        # Construct the record for this row
        record = {
            "id": str(id_array[i]),
            "txt": text_array[i],
            "company": companies_array[i],
            "quarter": quarters_array[i],
            "fqtr": datafqtr_array[i],
            "acutaldate": acutaldates_array[i],
            "month": months_arr[i],
            "day": days_arr[i]
        }
        grouped_data[year][i] = record

    output_dictlist = []
    
    # Iterate through sorted years to handle export and final list construction
    for target_year in target_years:
        tidy_dict = grouped_data[target_year]
        
        if export_jsons:
            output_file = Path(output_dir) / f"{source_short}_{target_year}.json"
            if verbose:
                print(output_file)
            with open(output_file, 'w', encoding='UTF-8') as f:
                json.dump(tidy_dict, f)
        
        # Wrap in a top-level key as per original requirement
        top_key = f"{source_short}_{target_year}"
        output_dictlist.append({top_key: tidy_dict})
        
    return output_dictlist, print_info


def make_hex_id(input_string: Any) -> str:
    """Generates a deterministic SHA-256 hexadecimal identifier from a given input.

    This function takes an input (converted to a string), encodes it as UTF-8, 
    and produces a unique 64-character hexadecimal hash to be used as unique 
    sentence ID 

    Args:
        input_string (Any): The value to be hashed. While typically a string, 
            any type that can be cast to a string will be accepted.

    Returns:
        str: The SHA-256 hash of the input represented as a hexadecimal string.
    """
    #cast to string and encode to bytes
    string_value = str(input_string)
    input_bytes = string_value.encode('utf-8')
    
    # Create a SHA-256 hash object, update with bytes
    sha256 = hashlib.sha256()
    sha256.update(input_bytes)
    
    # Get the hexadecimal representation of the hash
    hex_id = sha256.hexdigest()
    
    return hex_id


def make_tidy_article(valueset: Dict[str, Any]) -> str:
    """Cleans and normalizes a text article by removing noise and whitespace.

    This function extracts the 'txt' value from a dictionary and applies a 
    series of regular expression substitutions to remove non-breaking spaces, 
    carriage returns, tabs, newlines, multiple consecutive spaces, and 
    Byte Order Marks (BOM).

    Args:
        valueset (Dict[str, Any]): A dictionary containing the article data. 
            Must include the key 'txt' with the text content as a string.

    Returns:
        str: The cleaned and normalized version of the text.
    """
    this_art = valueset['txt']
    
    # Replace non-breaking spaces and carriage returns with standard spaces
    this_art = re.sub('\xa0', ' ', this_art)
    this_art = re.sub('\x0D', ' ', this_art)
    
    # Replace newlines, tabs, and carriage returns with a single space
    this_art = re.sub('\r|\n|\t', ' ', this_art)
    
    # Collapse multiple spaces into a single space
    this_art = re.sub('(  )+', ' ', this_art)
    this_art = re.sub('  ', ' ', this_art)
    
    # Remove leading space
    this_art = re.sub('^ ', '', this_art)
    
    # Remove Byte Order Marks (BOM)
    this_art = re.sub('\ufeff ', '', this_art)
    this_art = re.sub('\ufeff', '', this_art)
    
    return this_art



def run_pool(
    output_dictlist: List[Dict[str, Any]], 
    n_procs: int, 
    output_dir: str, 
    print_info: Dict[str, Any],
    chunk_size: int,
    verbose: bool
) -> None:
    """Orchestrates the parallel processing of year-based dictionaries using a process pool.

    After calculating an appropriate number of workers, submit dictionaries to the 
    `process_one_dict` function in the processor pool. 

    Args:
        output_dictlist (List[Dict[str, Any]]): A list of dictionaries, where each 
            dictionary represents a single year's data
        n_procs (int): The requested number of worker processes.
        output_dir (str): The directory path where processed outputs should be 
            stored (passed to workers if needed).
        print_info (Dict[str, Any]): Metadata about the current job, expected to 
            contain 'file' (filename) and 'y_splits' (number of years).
        chunk_size (int) : number of sents per conll file to print
        verbose (bool) : print all print statements


    Returns:
        None
    """
    # Calculate an appropriate number of workers
    actual_procs = min(n_procs, len(output_dictlist), os.cpu_count() or 1)
    
    print(
        f"Processing file {print_info['file']} into "
        f"{print_info['y_splits']} year-based files with {actual_procs} workers"
    )

    # make a partial function to pass to pool executor, freezing the specified pickleable args
    worker_funct = partial(process_one_dict, output_dir = output_dir, chunk_size=chunk_size, verbose=verbose)
    # Use ProcessPoolExecutor for CPU-bound tasks
    # _init_worker is used to initialize global variables for each child process
    with ProcessPoolExecutor(max_workers=actual_procs, initializer=_init_worker) as ex:
        # Schedule all processing tasks
        futures = [ex.submit(worker_funct, subdict) for subdict in output_dictlist]

        # Wrap as_completed in tqdm for a visual progress bar
        for future in tqdm(as_completed(futures), total=len(futures)):
            try:
                # result() will raise any exception that occurred during the execution of the task
                future.result()
            except Exception as e:
                # Use tqdm.write to avoid breaking the progress bar formatting
                tqdm.write(f"failed: {e}")
  
        

def make_conll_strings(articles_data: Dict[str, Any]) -> List[str]:
    """
    Converts a dictionary of article data into a list of CoNLL-formatted strings.

    Each string represents a sentence, containing metadata as comments (#) 
    followed by tokens and their indices. It handles speaker identification 
    at the start of sentences and tracks speaker continuity.

    Args:
        articles_data (Dict[str, Any]): A dictionary where keys are identifiers 
            and values are dictionaries containing article content (including 'txt').

    Returns:
        List[str]: A list of strings, where each string is a formatted CoNLL 
            block for a single sentence.
    """
    file_output = []

    for idx, (article_id, valueset) in enumerate(articles_data.items(), start=1):
        # Process article text and get NLP doc
        article_text = make_tidy_article(valueset)
        hex_id = make_hex_id(article_id)
        doc = _nlp(article_text)
        
        previous_speaker = "UNK"

        # Pre-generate metadata that is constant for the whole article
        meta_base = "".join([f'# {k}={v}\n' for k, v in valueset.items() if 'txt' not in k])

        for sent_idx, sentence in enumerate(doc.sents, start=1):
            current_sent_lines = []
            
            # Convert sentence to string for speaker detection
            sent_text = sentence.text
            match = SPEAKER_PATTERN.match(sent_text)

            speaker_name = previous_speaker
            offset = 0

            if match:
                # Extract speaker name and remove trailing colons/whitespace
                speaker_name = match.group(1).strip()
                # Calculate how many tokens the speaker prefix consumes
                # We find the index of the first character after the speaker prefix
                prefix_text = match.group(0)
                # Count tokens that make up the prefix to set the offset correctly
                offset = len([t for t in sentence if t.text in prefix_text]) 
                
                sent_text = sent_text[match.end():].strip()

            # Construct metadata block
            meta_lines = (
                f"# Article_num = {idx}\n"
                f"# sent_ID = {hex_id}-{sent_idx}\n"
                f"# sent_id_serial = {sent_idx}\n"
                f"{meta_base}"
                f"# speakername={speaker_name}\n"
                f"# text = {sent_text}\n"
            )
            current_sent_lines.append(meta_lines)

            # Add tokens to the CoNLL block
            for token_idx, token in enumerate(sentence):
                if token_idx >= offset:
                    # token_idx - offset + 1 ensures numbering starts at 1 for the actual content
                    line = f"{token_idx - offset + 1}\t{token.text}{CONLL_LINETAIL}"
                    current_sent_lines.append(line)

            # Join all lines for this sentence and add to final output
            file_output.append("".join(current_sent_lines) + "\n")
            previous_speaker = speaker_name

    return file_output

def process_one_dict(
    output_dictlist_item: Dict[str, Any], 
    output_dir: str, 
    chunk_size: int, 
    verbose: bool = False
) -> None:
    """
    Processes a single-item dictionary, converts its content to CoNLL format, 
    and saves the result into one or more chunked files.

    Args:
        output_dictlist_item (Dict[str, Any]): A dictionary containing one entry 
            where the key is the identifier and the value is the article data.
        output_dir (str): The directory path where the resulting .conll files 
            should be saved.
        chunk_size (int, optional): The maximum number of sentences per file. 
            Defaults to 50000, set from argparser
        verbose (bool, optional): If True, prints processing status to the console. 
            Defaults to False.

    Returns:
        None
    """
    if not output_dictlist_item:
        if verbose:
            print("Provided dictionary is empty. Skipping.")
        return

    # Efficiently get the first (and presumably only) key and value
    top_key, target_item = next(iter(output_dictlist_item.items()))

    if verbose:
        print(f"Processing {top_key}")

    # Convert the article data to CoNLL strings
    conll_strings = make_conll_strings(target_item)
    
    # Ensure the output directory exists
    base_path = Path(output_dir)
    base_path.mkdir(parents=True, exist_ok=True)

    # Loop through the data in chunks using a step-based range
    for i, start_idx in enumerate(range(0, len(conll_strings), chunk_size), start=1):
        end_idx = start_idx + chunk_size
        chunk = conll_strings[start_idx:end_idx]
        
        # Create filename: e.g., "ArticleID_part01.conll"
        file_name = f"{top_key}_part{i:02d}.conll"
        output_file = base_path / file_name

        # Write the chunk to the file
        with open(output_file, 'w', encoding='UTF-8') as f:
            f.writelines(chunk)

        if verbose:
            print(f'{output_file} exported')

  

def _init_worker() -> None:
    """
    Initializes the global spaCy NLP pipeline for the worker process.
    
    This function is designed to be used as an 'initializer' in a 
    multiprocessing Pool. By loading the model once per process 
    rather than once per task, we significantly reduce memory 
    overhead and startup time.
    """
    global _nlp
    # Loading a blank English model with only the sentencizer 
    # for maximum speed and minimum memory usage.
    _nlp = spacy.blank("en")
    _nlp.add_pipe("sentencizer")
    
  
def run_main(input_dir: str, output_dir: str, n_procs: int, chunk_size: int, export_jsons: bool, verbose: bool = False) -> None:
    """
    Main execution pipeline to process parquet files into CoNLL format.

    This function scans a directory for parquet files, extracts specific 
    columns, converts the data into dictionaries, and distributes the 
    processing across multiple CPU cores.

    Args:
        input_dir (str): Path to the directory containing .parquet files.
        output_dir (str): Path to the directory where conll files will be written.
        n_procs (int): Number of processor cores to use for parallel execution.
        chunk_size (int): Number of sents per conll file.
        verbose (bool, optional): If True, prints detailed progress to 
            the console. Defaults to False.

    Returns:
        None
    """
    print(f"Processing {input_dir} with {n_procs} requested cores.")
    
    # Columns required for processing; kept as a constant for maintainability
    TARGET_COLS = ['company', 'quarter', 'datafqtr', 'earnings_date', 'transcript']
    
    # get files from path
    input_path = Path(input_dir)
    parquet_files = sorted(list(input_path.glob("*.parquet")))

    if not parquet_files:
        print(f"No parquet files found in {input_dir}...")
        return

    for parquet_file in parquet_files:
        # 1. Load Parquet
        try:
            df = pd.read_parquet(parquet_file, columns=TARGET_COLS)
            if verbose:
                print(f"Loaded: {parquet_file.name}")
        except Exception as e:
            print(f"Error loading {parquet_file}: {e}")
            continue

        # 2. Transform data into arrays
        my_arrays = make_arrays(df)
        if verbose:
            print(f"Arrays built for {parquet_file.name}")

        # 3. Group arrays into dictionaries for processing
        # We pass the string version of the path to maintain compatibility with make_dicts
        output_dictlist, print_info = make_dicts(
            my_arrays, 
            str(parquet_file), 
            str(input_path),
            str(output_dir),
            export_jsons
        )
        if verbose:
            print(f"Dictionaries created for {parquet_file.name}")

        # 4. Execute parallel processing
        run_pool(output_dictlist, n_procs, output_dir, print_info, chunk_size, verbose)
        
        if verbose:
            print(f"Finished processing {parquet_file.name}\n" + "-"*30)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='''Process parquet formatted earnings calls
    
    Usage : 
      python3 /scripts/earnings_calls.py -input_dir /data/folder -n_procs 10
            
    ''')
    parser.add_argument(
        "-input_dir", type=str,help="path to folder with parquet files"
    )
    parser.add_argument(
        "-output_dir", type=Path, required=True, 
        help="output directory, in which results and subfolders will be placed"
    )
    parser.add_argument(
        "-n_procs", type=int, default=2,
        help="Number of worker processes requested"
    )
    parser.add_argument(
        "-chunk_size", type=int, default=50000,
        help="Number of sentences per CoNLL file"
    )
    parser.add_argument(
        "-export_jsons", action="store_true", default=False,
        help="export jsons before connlisation"
    )
    parser.add_argument(
        "-verbose", action='store_true', default=False,
        help="Include print statements with paths at file export"
    )
    args = parser.parse_args()
    
    input_dir = args.input_dir
    output_dir = args.output_dir
    n_procs = args.n_procs
    chunk_size = args.chunk_size
    export_jsons = args.export_jsons
    verbose = args.verbose
    run_main(input_dir, output_dir, n_procs, chunk_size, export_jsons, verbose)